#!/bin/sh

if [ $# -eq 0 ]; then
    echo "$0: Error: Specify pipeline run name." >&2
    echo "    Example usage:" >&2
    echo "    $0 some-component-name-on-push-fblf4" >&2
    exit 1
fi

if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
    if command -v kubectl > /dev/null; then
        KUBEARCHIVE_PR_LOGS_KUBECTL=kubectl
    fi
    if command -v oc > /dev/null; then
        KUBEARCHIVE_PR_LOGS_KUBECTL=oc
    fi
fi

if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
    echo "$0: Error: No Kubernetes client found" >&2
    exit 1
fi

response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka get pods -l tekton.dev/pipelineRun="$1" --archived -o json)
i=0
while [ "$response" = "KubeArchive authentication required: unauthorized" ] && [ "$i" -lt 10 ]; do
    if [ "$i" -gt 0 ]; then
        echo "Got unauthorized, retrying (${i} of 10)" >&2
    fi
    response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka get pods -l tekton.dev/pipelineRun="$1" --archived -o json)
    i=$((i+1))
done

for pod in $(printf "%s" "$response" | jq -r ".items |= sort_by(.metadata.creationTimestamp) | .items[].metadata.name"); do
    kubectl-ka-pod-logs "$pod"
done
